### ISSUE TITLE
Seccion "Primeros Pasos" 

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#15]
Podemos crear una sección dentro del portal donde compartamos enlaces de interes para dar los primeros pasos en Angular...

**Comment by Villanuevand** [comment]
La sección "Primeros Pasos" debe ser un repositorio único, o debe ser parte de alguno ya existente?. 
Me gustaría que varios de los miembros que están comenzando con el framework me den sus impresiones... 
@ngVenezuela/owners  @ngVenezuela/colaboradores

**Comment by gilberto1487** [comment]
En mi humilde opinión pienso que debería ser un repositorio único

**Comment by JMEspiz** [comment]
Estoy de acuerdo con Gilberto, un repositorio único donde se puedan acceder a todos los recursos.

**Comment by abr4xas** [comment]
Si, debe ser uno solo...

**Comment by cumanadigital** [comment]
Saludos, comparto la idea, un solo repositorio, y dentro de este agrupar por sub-niveles si lo consideran necesario

**Comment by FreakDroid** [comment]
Comparto lo mismo, una sola sección.

 Saludos.

**Comment by Villanuevand** [comment]
El repositorio [primeros-pasos](https://github.com/ngVenezuela/primeros-pasos) ya fué creado.
