### ISSUE TITLE
Fallas en el responsive

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#16]
Hay que realizar cambios en los media query para una mejor presentación de la web :)

**Comment by Villanuevand** [comment]
Está info puede ayudar... [Media Queries - Medidas Estandar](http://www.desarrolloweb.com/articulos/medidas-estandar-pantallas-media-queries.html)

**Comment by abr4xas** [comment]
Solucionado en parte en el último commit. Sigue abierta esta incidencia porque hay que modificar el media query del apartado de quienes somos con la información de los miembros de la comunidad.

**Comment by Villanuevand** [comment]
Perfecto, lo mantenemos entonces... Gracias Angel @abr4xas

**Comment by abr4xas** [comment]
Revise y no le veo fallas :sweat_smile: cerrado :stuck_out_tongue_closed_eyes:
