### ISSUE TITLE
Enlace a google groups

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#17]
Hay que agregar un enlace en el menu a google groups ya que incrustar el foro dentro de la pagina da algunos problemas.

`Refused to display 'https://groups.google.com/forum/embed/?place=forum/ngvenezuela&domain=http:…&showsearch=true&showpopout=true&parenturl=http%3A%2F%2Fngvenezuela.org.ve' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

Si alguien sabe como incrustarlo sin problemas por favor, abrir este ticket nuevamente :) mientras, se crea el enlace en el menu :)

**Comment by Villanuevand** [comment]
Ese error lo da donde? 
Al parecer hay un problema con CORS.
