### ISSUE TITLE
Solicito que me incluyan, quiero participar :)

### ISSUE THREAD

**Issue by code-andres** [ngVenezuela/ngvenezuela.github.io#18]
Vengo para aprender angular, la mejor manera sera participando en el codigo de la pagina u en algun otro proyecto que tengan.

**Comment by Villanuevand** [comment]
Muchas gracias por tú interés @code-andres ya estás dentro de los colaboradores de la organización. 
Si el logo de la misma no aparece en tú perfíl, debes entrar a la lista de colaboradores de ngVenezuela, y colocar el "perfíl" cómo publico.
