### ISSUE TITLE
Me gustaría participar

### ISSUE THREAD

**Issue by jobsamuel** [ngVenezuela/ngvenezuela.github.io#19]
Hola :smiley: 

Pasaba por acá decirles que me gustaría que me incluyeran en la organización. Estoy interesado en proponer proyectos y colaborar en los existentes. Asimismo, quiero compartir el poco conocimiento que tengo sobre Angular (y Material Angular) con los que lo necesitan.

**Comment by Villanuevand** [comment]
Excelente @jobsamuel ¡Bienvenido!
