### ISSUE TITLE
Cambiar el formato del logo de jpeg a SVG.

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#21]
Por recomendación de @pcimagenca se debe cambiar el formato del logo que se encuentra en el sitio web de `jpg` a `svg` con esto, se estará mejorando la velocidad de carga del mismo ya que con el formato actual, su renderización era muy lenta. 

Gracias a @pcimagenca por sus recomendaciones.

**Comment by abr4xas** [comment]
Recuerda que eso lo estamos tomando directamente desde la API de github
https://avatars.githubusercontent.com/u/11722566?v=3

![avatar](https://avatars.githubusercontent.com/u/11722566?v=3)

**Comment by Villanuevand** [comment]
@abr4xas Hay que actualizarlo, el que está actualmente es el antiguo.

**Comment by abr4xas** [comment]
Listo dude, ya lo cambie :smile: 
cierro esto.
