### ISSUE TITLE
Implementación del "tema" utilizado en el blog, en el portal. 

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#24]
Para llevar un orden en el portal, debemos implementar el tema usado en nuestro [blog](http://ngvenezuela.org.ve/blog/) en todo el sitio. 

Se asigna esta incidencia @abr4xas, el cual estará creando pequeñas tareas para hacer más sencillo de llevar.

**_PD**_: _Al terminar todas las "sub-tareas", puede darse como cerrada esta incidencia_

**Comment by abr4xas** [comment]
Cuales sub tareas quedan pendiente :sweat_smile:

**Comment by abr4xas** [comment]
@Villanuevand, que queda pendiente?? XD

**Comment by Villanuevand** [comment]
@abr4xas creo que nada...

**Comment by abr4xas** [comment]
Ok, entonces cerramos esto. Cualquier cosa, otro ticket
