### ISSUE TITLE
Se necesita una sección nueva llamada "Quiero unirme"

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#27]
En esta sección se planea incluir un formulario solicitando los siguientes datos:
- Nombre y Apellido
- Correo electrónico
- Usuario de Github

**Comment by Villanuevand** [comment]
Cerrado con el [PR-#29](https://github.com/ngVenezuela/ngvenezuela.github.io/pull/29)

**Comment by abr4xas** [comment]
Agregado en el commit 598ba56
