### ISSUE TITLE
Se necesita un texto descriptivo para la sección "Quieres unirte"

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#28]
Se necesita un texto descriptivo para la sección "Quieres unirte".

**Comment by Villanuevand** [comment]
Jajajaaj! Lo tomo yo...

**Comment by Villanuevand** [comment]
### **_Version 1**_

## 

Como dice nuestro slogan "Unir, Compartir y Aprender" en ngVenezuela, queremos conocerte y ayudarte a aprender y entender más como trabajar con Angular, en cualquiera de sus versiones.

Por ello hemos abierto  esta sección en nuestro portal, para poder recibir a todos aquellos desarrolladores interesado en el tema principal de nuestra comunidad.  Llena el formulario, y en muy poco tiempo te estaremos agregando a nuestra comunidad en Github.

**Comment by abr4xas** [comment]
@Villanuevand me parece genial tal como esta :+1:

**Comment by Villanuevand** [comment]
Cerrado con el [PR-#29](https://github.com/ngVenezuela/ngvenezuela.github.io/pull/29)
