### ISSUE TITLE
Secciones

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#3]
La aplicación debe contar con 3 secciones básicas. Estas secciones son:
- [Home](#home).
- [Repositorios](#repositorios)
- [Quienes Somos](#quienes-somos).
- [Contactos](#contactos).
#### Home

En estas sección se mostrará información básica de la comunidad, un párrafo descriptivo y nuestro lema.
#### Repositorios

En esta sección se mostrará información descriptiva de los repositorios.
#### Quienes Somos

En esta sección se mostrará información sobre que es la comunidad, cuales son nuestros propósitos.
#### Contactos

En esta sección se mostrará información sobre contactos con la comunidad. Puede ser cuentas de correo de administradores y colaboradores, redes sociales, organización en github y cualquier otro elemento que nos muestre como grupo organizado.

**Comment by abr4xas** [comment]
Vamos a tener algun tipo de "_manifesto_"?

**Comment by Villanuevand** [comment]
Si, deberíamos tener uno, hay que redactarlo @abr4xas . Hay que abrir un issue para eso.
Si puedes abrirlo, por favor.

**Comment by abr4xas** [comment]
Listo :)

**Comment by abr4xas** [comment]
Voy a cerrar esto, falta solo la sección de contacto, hay que buscar un servicio externo para eso. Luego se abre si es necesario.
