### ISSUE TITLE
Crear sitemap.xml

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#34]
Se debe crear un `sitemap.xml` para ir indexando la web en los diferentes buscadores.

Ejemplo:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://www.example.com/</loc>
      <lastmod>2005-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
</urlset>
```

Más info: http://www.sitemaps.org/protocol.html

**Comment by Villanuevand** [comment]
Aplica con Angular? La vista parcial ,será indexada???

**Comment by abr4xas** [comment]
> Un sitemap es un archivo en el que se pueden enumerar las páginas de tu sitio web para informar a Google y a otros motores de búsqueda sobre la organización del contenido del mismo.
> [fuente](https://support.google.com/webmasters/answer/156184?hl=es).

Ahora bien, no se si se puede crear un archivo con las características necesarias como lo explique arriba.

**Comment by Villanuevand** [comment]
Si, se exactamente que es un sitemap, solo que no sé, si por usar `angularJs` tendríamos los mismo efectos que un site normal, recuerda que nuestras vistas son dinámicas... Y tendríamos que escapar algunos caracteres.... Mira este ejemplo que hice algunos años, atencion en la url_ [Sitemap.xml en produccion](http://notitarde.com/sitemap.xml)....

**Comment by abr4xas** [comment]
Ese sitmap fue generado con xml-sitemaps.com. A mi se me ocurre que debe ser creado a mano total, no son muchas url xD

**Comment by Villanuevand** [comment]
No, la base fue generada con esa app, el resto los construi yo a mano...

**Comment by abr4xas** [comment]
Bueno, si sabes como hacerlo inténtalo y avisa para revisar :smile:

**Comment by abr4xas** [comment]
El sitemap debe quedar de esta forma:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>http://ngvenezuela.org.ve/</loc>
      <lastmod>2016-08-28</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://ngvenezuela.org.ve/#/repos</loc>
      <lastmod>2016-08-28</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://ngvenezuela.org.ve/#/quienes-somos</loc>
      <lastmod>2016-08-28</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://ngvenezuela.org.ve/#/quiero-unirme</loc>
      <lastmod>2016-08-28</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
   <url>
      <loc>http://ngvenezuela.org.ve/#/contacto</loc>
      <lastmod>2016-08-28</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
</urlset>
```

No creo que sea problema en hacer esto a mano. Que opinas @Villanuevand ?
