### ISSUE TITLE
Texto descriptivo - Sección Home

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#4]
Se necesita redactar el texto descriptivo que será colocado en la home del portal de la comunidad.

**Comment by abr4xas** [comment]
Alguien nos da una mano con esto?

**Comment by Villanuevand** [comment]
Yo puedo hacerlo, @abr4xas. Aunque ya tengo algo en mente, me gustaría saber, como imaginas este texto.

**Comment by abr4xas** [comment]
Realmente no :smile: pero, que piensas tu?

**Comment by Villanuevand** [comment]
Déjame redactar, para que leas lo que tengo en mente. @abr4xas

**Comment by abr4xas** [comment]
Agregado en el ultimo commit :+1:
