### ISSUE TITLE
Quitar las referencias al grupo de Google Groups

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/ngvenezuela.github.io#44]
En la vista *Contacto* y *Quienes somos*  se hace referencia al foro de Google Groups que quedó inactivo.

Yo lo puedo hacer dado que se dé el visto bueno.

**Comment by JMEspiz** [comment]
Yo apoyo la idea, que dice @Villanuevand  @jobsamuel @Skatox @abr4xas

**Comment by Villanuevand** [comment]
Si, hay que hacerlo, lastimosamente Google Groups se quedo detrás

**Comment by leocabeza** [comment]
¿Cual idea? @JMEspiz

**Comment by leocabeza** [comment]
Se cierra en #45
