### ISSUE TITLE
Texto Descriptivo - Sección Quienes Somos.

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#6]
Se necesita redactar el texto descriptivo que será colocado en la sección "Quienes Somos". El texto debe describir los principales propósitos de la comunidad.

**Comment by abr4xas** [comment]
**ngVenezuela** es un grupo de personas que se han organizado como comunidad con el objetivo de darse soporte mutuamente en el uso cotidiano de **Angular Js** donde dedicaremos a impartir y compartir conocimientos sobre este _framework_ a todos los interesados en aprenderlo.
La función primordial de esta comunidad es agrupar a los usuarios de **Angular Js** en **Venezuela**.

Nos encontramos en las siguientes redes sociales:
- ngVenezuela @ Google Groups
- ngVenezuela @ Facebook
- ngVenezuela @ Twitter
- +ngVenezuela @ Google Plus
- ngVenezuela @ Youtube

Que opinan?

**Comment by abr4xas** [comment]
Creo que así está un poco mejor:

**ngVenezuela** es un grupo de personas que se han organizado como comunidad con el objetivo de agrupar a todos los usuarios en Venezuela para obtener soporte mutuamente en el uso cotidiano de **Angular Js**. 

Esta comunidad dedicará tiempo en impartir y compartir conocimientos sobre este _framework_ creado por Google a todas aquéllas personas que estén interesadas en usar esta herramienta. 

Actualmente tenemos presencia en las siguientes redes sociales:
- ngVenezuela @ Google Groups
- ngVenezuela @ Facebook
- ngVenezuela @ Twitter
- ngVenezuela @ Google Plus
- ngVenezuela @ Youtube

Que opinan?

**Comment by Villanuevand** [comment]
Me gusta, solo cambiaría poco la estructura...

> **ngVenezuela** es un grupo de personas que se han organizado como comunidad con el objetivo de reunir a todos los usuarios del framework en nuestro país. Nos centramos en guiar, asesorar, impartir y compartir conocimientos  a las nuevas comunidades, y a desarrolladores que deseen aumentar sus habilidades con AngularJS.
> 
> Actualmente tenemos presencia en las siguientes redes sociales:
> - ngVenezuela @ Google Groups
> - ngVenezuela @ Facebook
> - ngVenezuela @ Twitter
> - ngVenezuela @ Google Plus
> - ngVenezuela @ Youtube

¿Qué dicen?

**Comment by abr4xas** [comment]
Bueno, voy a dar por cerrado este issues, más adelante si necesitamos realizar una modificación lo abrimos :)
