### ISSUE TITLE
Texto Descriptivo - Sección Contacto

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/ngvenezuela.github.io#7]
Se necesita redactar el texto descriptivo que será colocado en la sección "Contacto". 
El texto deberá englobar las redes sociales en las cuales la comunidad tenga presencia, así como el grupo en "Google Groups" y la organización en Github.

**Comment by abr4xas** [comment]
Alguna ayuda con esto?

**Comment by Villanuevand** [comment]
¿Que opinan de esto? ...  

> Queremos conocer a la mayor cantidad de Desarrolladores Angular que podamos. En ngVenezuela todos son bienvenidos, no importa si eres un joven padawan, o un Maestro Jedi consagrado, juntos podemos conquistar la galaxia. Acá podrás contactarnos estamos activos en: 
> - Google Groups: Acá hablamos de manera muy técnica, si tienes alguna duda acá es el sitio para compartirla.
> - Twitter: Toda la información actual sobre Angular, y otros temas de interés para nosotros, lo podrás conseguir, solo ¡Siguenos!.
> - Github: Còdigo, código, código... En Github tenemos nuestros proyectos totalmente expuestos para que puedas mirarlo, forkearlo, clonarlo, hacer `pull request` y aprendas como debe ser "codeando". 
> - Telegram: ¡OFF TOPIC!, nuestro día a día, en esta plataforma de mensajería, tendrás contacto directo con todos los miembros de la comunidad... Acá hablamos de cualquier cosa, y estamos en contacto permanente... No pierdas la oportunidad de conocer a los que conformamos ngVenezuela...
> 
> Si quieres formar parte de esta familia llamada **_ngVenezuela**_ no dejes de seguirnos en estás plataformas, y crece como developer intercambiando código, ideas y cualquier cosa que te parezca interesante,con nosotros. Visita la seccion [¡Quiero Unirme!](http://ngvenezuela.org.ve/#/quiero-unirme) ser miembro de la comunidad en GITHUB, y tener nuestro badge en tú perfil... 
> 
> ¡Entonces! ...  ¿Te nos unes?

**Comment by abr4xas** [comment]
Me parece genial.

Telegram, Google Groups etc etc con sus respectivos enlaces, cierto? xD

**Comment by abr4xas** [comment]
Se agregan los cambios en el próximo commit.
