### ISSUE TITLE
Manifesto

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#8]
Crear un "_manifesto_" para la comunidad AngularJs-Ve.

Podemos tomar como ejemplo el [Código de conducta Ubuntu-Ve](http://www.ubuntu.org.ve/codigodeconducta).

**Comment by Villanuevand** [comment]
Se ha hecho un [fork](https://github.com/ngVenezuela/Manifesto) o bifurcación del manifesto de nuestra comunidad hermana [Venezuela.js](https://github.com/vzllajs/).

Queda abierto el debate y las contribuciones. Así cómo también, si redactaremos un código de Conducta adicional.

**Comment by abr4xas** [comment]
Trabajemos esto @Villanuevand se nos ha quedado "en el aparato"

**Comment by Villanuevand** [comment]
@abr4xas Creo que así estaría listo, se hicieron las modificaciones pertinentes para adaptarlo a la ngVenezuela, creo que así está bien puntual. Si tienes alguna idea para complementar o extender este manifesto, pues discutamosla.

**Comment by Villanuevand** [comment]
Hace unos días se hizo una modificación pequeña... 
Se puede dar como cerrado este issue.
