### ISSUE TITLE
Página estática 

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/ngvenezuela.github.io#9]
Saludos,

Para ir generando el contenido de la página web de ngVenezuela que gestor de contenidos estático vamos a usar?
- jekyll
- pelican

Yo le doy +1 a pelican porque tengo tiempo trabajando con el y me parece mucho más fácil que jekyll

**Comment by abr4xas** [comment]
Estas son las páginas oficiales de los proyectos:
- http://blog.getpelican.com/
- http://jekyllrb.com/

**Comment by abr4xas** [comment]
@alexsalas seguro que se va por jekyll xD

**Comment by Villanuevand** [comment]
Tambien existe [Octopress](http://octopress.org/), que pinta también cómo una buena solución.
Acá un tutorial sobre su uso con Github...

 [Tutorial: Create a Blog With Octopress and Host It in Github Pages](http://miguelcamba.com/blog/2013/04/22/tutorial-create-a-blog-with-octopress-and-host-it-in-github-pages/)

**Comment by ajsb85** [comment]
:raised_hands: +1 @jekyll/jekyll

**Comment by abr4xas** [comment]
Yo no me siento cómodo con octopress/jekyll por ruby... Para mi es más fácil hacer `pip install pelican` y listo...

**Comment by Villanuevand** [comment]
Yo estoy en blanco con las diferentes opciones! :pensive:

**Comment by ajsb85** [comment]
pelican + travis es buena solución, pero estamos tratando con Angular, hay soluciones Angular xD

**Comment by Villanuevand** [comment]
Existen issues abiertos donde se plantea el desarrollo de nuestro sitio usando Angular. Por lo cual podemos dar por cerrado este.
